import { NextResponse } from 'next/server';
import { exec } from 'child_process';
import { promisify } from 'util';
import path from 'path';
import fs from 'fs/promises';
import prisma from '@/lib/prisma';
import bcrypt from 'bcryptjs';

const execAsync = promisify(exec);

export async function POST(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const userId = searchParams.get('userId');

    if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    const user = await prisma.user.findUnique({ where: { id: userId } });
    if (!user || user.role !== 'admin') return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const formData = await request.formData();
    const file = formData.get('file') as File;
    const password = formData.get('password') as string;

    if (!file || !password) {
      return NextResponse.json({ error: 'Arquivo e senha são obrigatórios' }, { status: 400 });
    }

    // Verify admin password
    const isMatch = await bcrypt.compare(password, user.password);
    if (!isMatch) {
      return NextResponse.json({ error: 'Senha incorreta. Restauração bloqueada.' }, { status: 403 });
    }

    const tmpDir = path.join(process.cwd(), 'backups', 'tmp');
    await fs.mkdir(tmpDir, { recursive: true });
    
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    
    const tmpFile = path.join(tmpDir, `restore_${Date.now()}.sql.gz`);
    await fs.writeFile(tmpFile, buffer);

    const dbUrl = process.env.DATABASE_URL;
    if (!dbUrl) throw new Error("DATABASE_URL not found");

    // Important: we assume the file is a gzip of SQL generated by pg_dump --clean
    const cmd = `zcat "${tmpFile}" | psql "${dbUrl}"`;
    await execAsync(cmd);

    // Clean up
    await fs.unlink(tmpFile);

    return NextResponse.json({ success: true });

  } catch (error: any) {
    console.error('[Backup Restore API] Error:', error);
    return NextResponse.json({ error: error.message || 'Falha ao restaurar banco' }, { status: 500 });
  }
}
